name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        cd src/VDesk
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../publish/vdesk -r win-x64 --self-contained true /p:UseAppHost=true
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vdesk Package
        path: publish/vdesk
